name: Launcher Build

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: 18

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "yarn"

    - name: Install Dependencies
      run: yarn

    - name: Fix Linux Build
      run: sudo apt update && sudo apt install -y libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev

    - name: Build Launcher Binary
      run: yarn build
      
    - name: Dependency Build Cache
      uses: actions/cache@v3.0.8
      with:
        path: src-tauri/target/release
        key: target-1

    - name: Upload Launcher Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Launcher
        path: src-tauri/target
